# Generated by Django 2.2.7 on 2019-11-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('pk',), 'verbose_name': 'Producto', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='name',
            field=models.CharField(help_text='Nombre del producto', max_length=32),
        ),
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='precio del producto', max_digits=6),
        ),
    ]
