# Generated by Django 2.2.7 on 2019-11-16 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191116_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='active',
            field=models.BooleanField(default=True, help_text='Producto activo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='date_update',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de actualización del producto'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product-images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProducTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField(max_length=48)),
                ('description', models.TextField(blank=True, null='')),
                ('active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(blank=True, null=True, to='main.Producto')),
            ],
        ),
    ]
