# Generated by Django 2.2.7 on 2019-11-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_activemanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productag',
            name='products',
            field=models.ManyToManyField(blank=True, to='main.Producto'),
        ),
    ]
